server/spring_action_cleaning.sql

Thank you for contributing! To help the review process, please provide the following:
Provide links to any associated pull requests or issues. You can use `#123` to link to a PR or issue in this repository, or `user/repo#123` to link to other repositories.
[code of conduct]: https://github.com/textbook/starter-kit/blob/master/.github/CODE_OF_CONDUCT.md
[contributing guide]: https://github.com/textbook/starter-kit/blob/master/.github/CONTRIBUTING.md

Clean source file.

---

server/spring_action_cleaning.sql

Thank you for contributing! To help the review process, please provide the following:
Provide links to any associated pull requests or issues. You can use `#123` to link to a PR or issue in this repository, or `user/repo#123` to link to other repositories.
[code of conduct]: https://github.com/textbook/starter-kit/blob/master/.github/CODE_OF_CONDUCT.md
[contributing guide]: https://github.com/textbook/starter-kit/blob/master/.github/CONTRIBUTING.md

Renamed tables.

---

client/src/App.js
client/src/components/CreateWorkerForm.js
client/src/components/index.js
client/src/pages/CreateWorker.js
client/src/pages/index.js
client/src/service.js
server/api.js

Changed code to reflect new table names.

Change code to reflect new table names

---

client/src/App.js
client/src/components/ShowWorkersForm.js
client/src/components/index.js
client/src/pages/ShowWorkers.js
client/src/pages/index.js
client/src/service.js

Workers list is added. Nothing more.
Related [card on Trello](https://trello.com/c/3kpkrCOP/38-admin-can-see-list-of-cleaners). We need a list of cleaners so later on admin can select specific cleaner, update, assign to a job.

Wokers list

---

client/src/App.js
client/src/components/Jobs/JobsList.js
client/src/components/Jobs/JobsTableBody.js
client/src/components/Jobs/JobsTableHead.js
client/src/components/UI/Spinner.js
client/src/components/index.js
client/src/hooks/useFetch.js
client/src/pages/Jobs.js
client/src/pages/index.js

This is [the trello card](https://trello.com/c/Ljv9BFwB/40-admin-can-see-a-list-of-jobs) for this PR. This page is for listing ongoing jobs, so admins can see jobs. Later on will need to add edit and add job options.

List of jobs page

---

client/src/App.js
client/src/components/ShowCustomers.js
client/src/components/index.js
client/src/pages/Customers.js
client/src/pages/index.js
client/src/service.js

This page displays a list of customers. This is the [trello card](https://trello.com/c/MCEAzKnx/39-admin-can-see-a-list-of-customers) for this pull request.

Customers list

---

client/src/App.js
client/src/api.js
client/src/components/CreateCustomer/BranchForm.js
client/src/components/CreateCustomer/Branches.js
client/src/components/CreateCustomer/BranchesTable.js
client/src/components/CreateCustomer/CreateCustomerForm.js
client/src/components/CreateCustomer/Modal.js
client/src/components/CreateJob/SelectCustomer.js
client/src/components/CreateJob/SelectWorker.js
client/src/components/CreateWorkerForm.js
client/src/components/Jobs/JobsTableBody.js
client/src/components/ShowCustomers.js
client/src/components/index.js
client/src/hooks/useFetch.js
client/src/pages/CreateCustomer.js
client/src/pages/EditCustomer.js
client/src/pages/index.js
client/src/service.js
server/routes/branches.js

This PR includes little tweaks for general look and use. Sorry that I included them in a PR together with adding and branches functionality. I just wanted to make it look better before the meeting with the client.

Adding branches

---

client/src/components/CreateCustomer/BranchForm.js
client/src/components/CreateCustomer/Branches.js
client/src/components/CreateCustomer/BranchesTable.js
client/src/pages/CreateCustomer.js
client/src/util/helpers.js
server/routes/branches.js

Added checking in backend and a checkbox field in frontend for selecting a branch as a main one. Main branch is used when a new job is created and a client selected, then the main branch will be automatically selected for the admin. 
Also added helper function `sortDescByABC` inside `util` directory. This function expects to get array of object as first parameter and a key name of an object as a second. Then it sorts the array by that object key value in descending order by abc.

Set main branch

---

client/src/App.js
client/src/components/UI/AddNewButton.js
client/src/components/index.js
client/src/pages/Customers.js
client/src/pages/Jobs.js
client/src/pages/ShowWorkers.js

Moved text links out of homepage and added links as buttons in each page with a table in the top right corner like the wireframe [examples here](https://miro.com/app/board/o9J_lcFX0FA=/?moveToWidget=3074457352560753360&cot=14).

Add button for adding new clients, workers and jobs

---

.eslintignore
.eslintrc.json
client/src/components/CreateCustomer/BranchesTable.js
client/src/components/ShowWorkersTable.js
client/src/util/helpers.js
package-lock.json
package.json
server/routes/jobs.js
server/util/formatJobs.js
tests/formatJobs.test.js
tests/helpers.test.js

Added tests for date transformation and sorting helper functions.

Test dates

---

client/src/components/CreateCustomer/BranchForm.js
client/src/components/CreateCustomer/BranchModal.js
client/src/components/CreateCustomer/BranchesTable.js
client/src/components/CreateCustomer/CreateCustomerForm.js
client/src/components/CreateCustomerReport.js
client/src/components/CreateJob/SelectWorker.js
client/src/components/CreateWorkerForm.js
client/src/components/CreateWorkerReport.js
client/src/pages/CreateJob.js
client/src/pages/HomePage.js
client/src/pages/Jobs.js

Little UI and UX tweaks done together today.

UI changes

---

client/src/App.js
client/src/components/Jobs/JobsTableBody.js
client/src/components/Jobs/Worker/WorkerJobInfo.js
client/src/components/Jobs/Worker/WorkerJobsList.js
client/src/components/Jobs/Worker/WorkerJobsTableBody.js
client/src/components/Jobs/Worker/WorkerLogTimeForm.js
client/src/components/Navigation.js
client/src/components/Recurring/RecurringJobsTableBody.js
client/src/components/UI/BackButton.js
client/src/components/index.js
client/src/pages/WorkerHomePage.js
client/src/pages/WorkerJobPage.js
client/src/pages/WorkerJobs.js
client/src/pages/index.js
client/src/service.js
client/src/util/helpers.js
server/routes/jobs.js
server/routes/workers.js
server/spring_action_cleaning.sql
server/util/formatJobs.js
tests/formatJobs.test.js
tests/helpers.test.js

Mostly updated code to be aware of two different roles - "admin" and "worker". If you want to log in as a worker you can do it with email: `worker@dot.com` password: `ABC123$%^` Otherwise you can assign/change roles in auth0 dashboard for any user.
As I understand we want to let worker send feedback message without start and end times, so currently it lets to do that. Also it allows worker to remove times and basically change job status from completed to missing.
The feedback which worker left about the job still needs to be displayed in jobs table for admins (probably an icon button at the end of the table row which would open a modal).
And some information for workers about what can be done (or how it should be used) on the jobs page still needs to be added.

Cleaner journey

---

server/spring_action_cleaning.sql

Thank you for contributing! To help the review process, please provide the following:
Fix trailing comma error in `spring_action_cleaning.sql` file.
Don't forget to run `npm run populatedb:local` after adding this.

Remove trailing comma

---

client/src/components/Jobs/JobsTableBody.js
client/src/components/Jobs/JobsTableHead.js
client/src/components/Jobs/Worker/WorkerFeedbackIconButton.js
client/src/components/Jobs/Worker/WorkerFeedbackModal.js
client/src/components/UI/TextIcon.js
server/util/formatJobs.js
tests/formatJobs.test.js

Added extra column at the end of the jobs list table. When worker adds message (with or without start and end times) in the jobs list table admin will see a text icon on that table row. On icon click it will show a modal with the message from the worker.

Worker message icon

---

client/src/components/Jobs/Worker/WorkerJobsList.js
client/src/contexts/ContextProviders.js
client/src/contexts/WorkerJobs.js

Thanks to @GTabala for telling that context is missing for workers Jobs list. Just added it.

Add use of context for worker jobs

---

client/src/App.js
client/src/components/Footer/Footer.js
client/src/components/HomepageText.js
client/src/components/homepageImg.js
client/src/scss/index.scss
package-lock.json

Pull request on additional changes left out

Recommended changes effected

---

client/src/components/CreateCustomer/CreateCustomerForm.js
client/src/components/CreateJob/SelectCustomer.js
client/src/components/CreateJob/SelectWorker.js
client/src/components/CreateWorkerForm.js
client/src/pages/CreateCustomer.js
client/src/pages/EditCustomer.js
client/src/pages/EditWorker.js
client/src/service.js
server/routes/customers.js
server/routes/workers.js
server/spring_action_cleaning.sql

- Add option to archive worker
- Add option to archive customer

Add option to archive worker and customer

---

client/src/components/CreateJob/SelectBranch.js
client/src/components/CreateJob/SelectCustomer.js
client/src/components/Jobs/Worker/WorkerJobInfo.js
client/src/components/Jobs/Worker/WorkerLogTimeForm.js
client/src/util/helpers.js
server/routes/jobs.js
server/spring_action_cleaning.sql

- Add information to message to worker
- Show job details even when they are empty
- Populate job details with branch default details

Show more info to worker, auto populate details

---

client/src/components/CreateCustomer/CreateCustomerForm.js
client/src/components/Jobs/DateFilter.js
client/src/components/Jobs/JobsList.js
client/src/components/Jobs/Worker/WorkerHelpModal.js
client/src/components/Jobs/Worker/WorkerJobsList.js
client/src/components/Jobs/Worker/WorkerLogTimeForm.js
client/src/components/Navigation.js
client/src/scss/index.scss
server/spring_action_cleaning.sql

Final final changes

---

client/src/components/Recurring/ChangeWorkerButton.js
client/src/components/Recurring/RecurringJobsTableBody.js
client/src/components/Recurring/WorkerFilter.js
client/src/pages/Recurring.js

It was a strange race condition bug with two useEffects updating the same `useState` hook. So I extracted workers for selection data into separate `useState` hook and everything now seems ok!

Fix missing workers names bug

---

README.md
client/src/App.js
client/src/components/CreateCustomerReport.js
client/src/components/CreateWorkerReport.js
client/src/components/Reports/ResultPage.js
client/src/components/Reports/ResultTableBody.js
client/src/components/SelectDateU.js
client/src/contexts/CustomerReport.js
client/src/contexts/WorkerReport.js
client/src/scss/index.scss
server/routes/reports.js
server/spring_action_cleaning.sql

Detaled reports

---

client/src/components/CreateCustomerReport.js
client/src/components/CreateWorkerReport.js
client/src/components/Reports/ResultPage.js
client/src/components/UI/BackButton.js

Fix problems with error.

---

client/src/components/CreateCustomer/BranchesTable.js
client/src/components/CreateCustomer/CreateCustomerForm.js
client/src/components/CreateJob/Modal.js
client/src/components/CreateJob/SelectBranch.js
client/src/components/CreateJob/SelectCustomer.js
client/src/components/CreateJob/SelectWorker.js
client/src/components/HomepageText.js
client/src/components/Jobs/Worker/WorkerJobInfo.js
client/src/components/Navigation.js
client/src/components/Recurring/RecurringJobsTableBody.js
client/src/components/Recurring/RecurringJobsTableHead.js
client/src/pages/CreateCustomer.js
client/src/pages/CustomerReports.js
client/src/pages/Customers.js
client/src/scss/index.scss

I added a few tweaks to fix issues which were annoying me for some time.

Little tweaks

---

client/src/pages/Recurring.js

It had two `useEffect` calls doing pretty much the same thing. I forgot to remove the old one...

Remove extra useEffect

---

client/src/components/Jobs/JobsTableBody.js
client/src/components/Reports/ResultPage.js
client/src/components/Reports/ResultTableBody.js
client/src/components/Reports/ResultTableHead.js
server/routes/reports.js

Reports explanation

---

client/src/components/Reports/ResultTableBody.js
server/routes/reports.js

Planned duration has been added.

---

README.md
client/src/App.js
client/src/components/CreateJob/SelectWorker.js
client/src/components/Reports/CreateWorkerReport.js
client/src/components/Reports/GeneralWorkerResultPage.js
client/src/components/Reports/GeneralWorkerTable.js
client/src/components/UI/BackButton.js
client/src/components/index.js
client/src/contexts/WorkerReport.js
client/src/pages/GeneralWorkerReport.js
client/src/pages/index.js
server/routes/reports.js

If you do not select a specific cleaner in the report on cleaners, then a report is generated for all cleaners for this period. When a specific line is selected from the report result, a report is generated for the user from this line. The format of the user's report (detailed or not) is determined by the setting on the report settings page.

General report of cleaners.

---

client/src/App.js
client/src/components/Reports/CreateWorkerReport.js
client/src/components/Reports/GeneralWorkerResultPage.js
client/src/components/Reports/GeneralWorkerTable.js
client/src/components/UI/BackButton.js
client/src/components/index.js
client/src/pages/GeneralWorkerReport.js
client/src/pages/index.js
server/routes/reports.js

If you do not select a specific cleaner in the report on cleaners, then a report is generated for all cleaners for this period. When a specific line is selected from the report result, a report is generated for the user from this line. The format of the user's report (detailed or not) is determined by the setting on the report settings page.

General report of cleaners

---

client/src/components/CreateJob/SelectCustomer.js
client/src/components/Reports/CreateBranchReport.js
client/src/components/UI/BackButton.js

Set to "All addresses" when choosing a customer and go back in the general report after running the report for certain branch.

Fixed problem back button

---

client/src/App.js
client/src/components/CreateJob/SelectBranch.js
client/src/components/CreateJob/SelectCustomer.js
client/src/components/Reports/CreateBranchReport.js
client/src/components/Reports/CreateCustomerReport.js
client/src/components/Reports/GeneralCustomerResultPage.js
client/src/components/Reports/GeneralCustomerTable.js
client/src/components/Reports/GeneralWorkerTable.js
client/src/components/UI/BackButton.js
client/src/contexts/BranchReport.js
client/src/pages/GeneralCustomerReport.js

If a client is not selected in the branch report, a report is generated that is similar to a list of all customers for which work was performed in the current period; when you click on a specific line, a list of works by branches of this customer is generated.

Improved the branch report.

---

README.md
client/src/App.js
client/src/components/Navigation/Navigation.js
client/src/components/Reports/GeneralReport.js
client/src/components/Reports/GeneralReportResultPage.js
client/src/components/Reports/GeneralTable.js
client/src/components/index.js
client/src/contexts/ContextProviders.js
client/src/contexts/GeneralReport.js
client/src/pages/GeneralReportPage.js
client/src/pages/GeneralReportResultPage.js
client/src/pages/index.js
client/src/scss/index.scss
server/routes/reports.js
server/util/helpers.js

General report

---

client/src/components/Reports/GeneralBranchTable.js
client/src/components/Reports/GeneralCustomerTable.js
client/src/components/Reports/GeneralWorkerTable.js
client/src/components/Reports/ResultBranchTableBody.js
client/src/components/Reports/ResultTableBody.js

Fixed duration format function

---

client/src/components/Reports/GeneralReport.js
client/src/components/Reports/GeneralReportResultPage.js
client/src/components/Reports/GeneralTable.js

Hide-show the feedback column in the General report.

Hide-show feedback column

---

server/routes/workers.js

Currently, when adding a new cleaner with an email that already exists there are errors thrown in the console but the UI is not updated. With these changes, email input would be highlighted and an error message would be shown.

Add check for existing email and send error to frontend

---

README.md
client/src/components/Reports/BranchResultPage.js
client/src/components/Reports/GeneralBranchResultPage.js
client/src/components/Reports/GeneralBranchTable.js
client/src/components/Reports/GeneralCustomerResultPage.js
client/src/components/Reports/GeneralCustomerTable.js
client/src/components/Reports/GeneralTable.js
client/src/components/Reports/GeneralWorkerResultPage.js
client/src/components/Reports/GeneralWorkerTable.js
client/src/components/Reports/ResultBranchTableBody.js
client/src/components/Reports/ResultPage.js
client/src/components/Reports/ResultTableBody.js
server/routes/reports.js
server/util/helpers.js

Reports and routes have been brought to a single style.

Refactoring reports

---

server/controllers/branches.js
server/controllers/customers.js
server/controllers/jobs.js
server/controllers/reports.js
server/controllers/workers.js
server/routes/branches.js
server/routes/customers.js
server/routes/jobs.js
server/routes/reports.js
server/routes/workers.js
server/util/helpers.js
server/validation/branches.js
server/validation/checkErrors.js
server/validation/customers.js
server/validation/index.js
server/validation/jobs.js
server/validation/workers.js

I extracted routes validation and controllers into separate folders. This way our routes becomes more readable. Validation is also separated and easier to track and change.

Refactor routes

---

client/src/pages/CreateJob.js

This solution solves the problem of returning after saving an existing job.

History problem
